# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: earubioc.MDK
PackageVersion: 2.9.1
PackageLocale: en-US
Publisher: VDC Process Lab
PublisherUrl: https://vdcprocesslab.com/
PublisherSupportUrl: https://github.com/earubioc/mdk/issues
PackageName: MDK
PackageUrl: https://github.com/earubioc/mdk
License: MIT
LicenseUrl: https://github.com/earubioc/mdk/blob/main/LICENSE
Copyright: Copyright © 2026 Edgar A. Rubio C. / VDC Process Lab
ShortDescription: Simple Markdown editor for Windows
Description: A clean Markdown editor with live preview, PDF export, themes and document comparison. No ads, no account.
Moniker: mdk
Tags:
- markdown, editor, md
ReleaseNotesUrl: https://github.com/earubioc/mdk/releases/tag/v2.9.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
